### PR TITLE
update extending.md

### PR DESCRIPTION
**Pull request by HighHarmonics2**
Added info sections about mono/stereo and parameters where you don't need list values.

@tmhglnd feel free to edit or reject these changes.

### CODE REVIEW

**Comment by HighHarmonics2** [comment]
Added additional commit

**Comment by tmhglnd** [comment]
Thanks for this! Looks great!

**Comment by HighHarmonics2** [comment]
@tmhglnd 
The changes aren't deployed yet to the documentation site. It looks like you have a GH workflow setup to handle the Docusaurus deployment step to GH pages? I'm sure you are aware and I realize this is low priority. My reason to ask is just to  validate my edits and make sure I didn't miss something. In Tidal-doc there is an automated workflow that runs when changes are detected.

**Comment by tmhglnd** [comment]
I am aware yes, I'll do this later. This is because the docs are deployed from the `/mercury` github instead of this `/mercury-docs`, I haven't found a workaround/custom workflow for that yet. If you know how to set this up i'd be interested to know.

**Pull request merged**
